### ISSUE TITLE
[BUG] dynamoose attampts to create table?

### ISSUE THREAD

**Issue by softmarshmallow** [dynamoose/dynamoose#1051]
I'm using serverless + nestjs + dynamodb + dynamoose for deploying my serverless lambda application. 

in my serverless config, i have

``` yml
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  apiGateway:
    minimumCompressionSize: 1024
  environment: 
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    DYNAMODB_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

```

Which should work, on  CRUD operations, but when i deploy it i get the AccessDeniedException on runtime.
Which means, dynamoose is trying to create new table, or atleast accessing sort of code related to it. How will i be able to disable this option on usage with dynamoose?

```
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "AccessDeniedException: User: arn:aws:sts::00000:assumed-role/----dev-us-west-1-lambdaRole/scene-store-dev-main is not authorized to perform: dynamodb:CreateTable on resource: arn:aws:dynamodb:us-west-1:22222:table/s----dev",
    "reason": {
        "errorType": "AccessDeniedException",
        "errorMessage": "User: arn:aws:sts::----:assumed-role/----dev-us-west-1-lambdaRole/----dev-main is not authorized to perform: dynamodb:CreateTable on resource: arn:aws:dynamodb:us-west----:table/----dev",
        "code": "AccessDeniedException",
        "message": "User: arn:aws:sts::-----:assumed-role/----us-west-1-lambdaRole/-----main is not authorized to perform: dynamodb:CreateTable on resource: arn:aws:dynamodb:us-west-1:-----dev",
        "time": "2020-11-25T03:43:59.068Z",
        "requestId": "-------",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 31.37373858840934,
        "stack": [
            "AccessDeniedException: User: arn:aws:sts::--:assumed-role/-----main is not authorized to perform: dynamodb:CreateTable on resource: arn:aws:dynamodb:us-west---table/----dev",
            "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
            "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
```
