### ISSUE TITLE
[FEATURE] Update docs : add serverless configuration guide

### ISSUE THREAD

**Issue by softmarshmallow** [dynamoose/dynamoose#1052]
After spending few hours, i managed dynamoose to work with serverless for lambda deployment.

first, 

explicit permissions are required.
A: - dynamodb:DescribeTable

full example

``` yml
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  apiGateway:
    minimumCompressionSize: 1024
  environment: 
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    DYNAMODB_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

```

Secondly, disable create option on new model written via code.
https://github.com/dynamoose/dynamoose/issues/1051

``` ts
export const Scene = dynamoose.model(TABLE, SceneScheam, {
    create: false
});
```
