### ISSUE TITLE
[BUG] ERROR Unhandled Promise Rejection "errorType": "Runtime.UnhandledPromiseRejection" Table already exists

### ISSUE THREAD

**Issue by yeukfei02** [dynamoose/dynamoose#1114]
```
2021-02-05T03:18:44.062Z	1abd6db3-2523-4759-a9b6-4efb26d1bf14	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
    "reason": {
        "errorType": "ResourceInUseException",
        "errorMessage": "Table already exists: k11-open-api-record-time-prod",
        "code": "ResourceInUseException",
        "message": "Table already exists: k11-open-api-record-time-prod",
        "time": "2021-02-05T03:18:44.059Z",
        "requestId": "HD5AFEAVI78KITG8LEI8KKVRVVVV4KQNSO5AEMVJF66Q9ASUAAJG",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 110.1554075775096,
        "stack": [
            "ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
            "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)",
            "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:495:21)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

why will show this error, I just follow the tutorial to create schema and model

**Comment by fishcharlie** [comment]
Thank you for your issue. This project is successful due to the reports and help we get from the community in improving the project.

This project has a lot of guidelines that help ensure the project continues to run smoothly and project maintainers aren't burdened with a lot of back and forth discussion in order to advance the project and resolve issues.

**Sadly it has been determined that your issue does not follow those guidelines.**

This could be due to the following *checked* items (unchecked items were satisfied, found irrelevant, or not checked):

General

- [x] Issue template not filled out
- [x] Issue is unclear
- [x] Issue doesn't explain what has already been tried and what attempts you have made to resolve the issue

Example (MCVE)

- [ ] Example provided has too much irrelevant code and is not considered minimal (*Minimal*)
- [ ] Example provided has undefined variables that make it impossible to reproduce (*Complete*)
- [ ] Example provided is missing code necessary to reproduce the error (*Complete*)
- [ ] When trying to reproduce example provided I did not receive the same error message as described in issue (*Verifiable*)
- [x] No example provided (*Example*)

Error

- [ ] No error included
- [ ] Error included is unclear or confusing
- [ ] No stack trace included in error
- [ ] No information about current and expected result

Read through our [contributing guidelines](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md) for more information about what is expected when submitting issues.

If you have any questions about why this message was posted on your issue, please comment below with your specific question and we'd be happy to discuss with you further. If you believe you have followed the guidelines and still received this error message, please comment your reasoning below for why you believe you have followed the guidelines checked above, and we'll take another look at it.

While we understand that these guidelines create a larger burden on you, it is critical you follow them. The project maintainers have to handle everyone's issues while you only have to write yours, so it is imperative you make our jobs easier and help save us time by following the guidelines.

In order to proceed, please create a *new issue* ensuring you address all guidelines checked above (while also taking note to not violate any guidelines you followed).

---

Additional Information:



---

Disclosure: This was based on a [GitHub Saved Reply](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/working-with-saved-replies). The checkboxes were manually checked by myself based on your original issue.

**Comment by yeukfei02** [comment]
hello, I will add more how I configure this

I am using `serverless framework` + `aws lambda`

this is the model:

```
// import env from 'dotenv';
// env.config();

import dynamoose from 'dynamoose';
dynamoose.aws.sdk.config.update({
  accessKeyId: process.env.MY_AWS_ACCESS_KEY,
  secretAccessKey: process.env.MY_AWS_SECRET_ACCESS_KEY,
  region: 'ap-southeast-1',
});

const recordTimeSchema = new dynamoose.Schema(
  {
    id: String,
    partner_name: String,
    partner_store_code: {
      type: String,
      rangeKey: true,
    },
  },
  {
    saveUnknown: true,
    timestamps: {
      createdAt: 'createdAt',
      updatedAt: 'updatedAt',
    },
  },
);

let tableName = '';
if (process.env.NODE_ENV === 'development' || process.env.NODE_ENV === 'test') {
  tableName = 'k11-open-api-record-time-uat';
} else {
  tableName = 'k11-open-api-record-time-prod';
}

const recordTimeModel = dynamoose.model(tableName, recordTimeSchema, {
  create: false,
  waitForActive: { enabled: false },
});

export default recordTimeModel;
```

before I am using this for all staging and production env.

```
const recordTimeModel = dynamoose.model(tableName, recordTimeSchema);
```

but after the error show, I made a change of this:

```
const recordTimeModel = dynamoose.model(tableName, recordTimeSchema, {
  create: false,
  waitForActive: { enabled: false },
});
```

btw is it related to this lib `aws-sdk` problem or aws lambda problem?
because I believe without setting those 2 flag to false, I am able to `createtable` + `describetable` in dynamodb.

Thanks!

**Comment by yeukfei02** [comment]
`serverless.yml`


```
org: keysocapp
app: k11-open-api
service: k11-open-api

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  apiName: k11-open-api-dev
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: development
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
    K11_OPEN_API_JWT_SECRET_DEV: ${param:K11_OPEN_API_JWT_SECRET_DEV}
    K11_OPEN_API_JWT_SECRET_PROD: ${param:K11_OPEN_API_JWT_SECRET_PROD}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: K11 Open Api Staging
  lambdaHashingVersion: 20201221
  # vpc:
  #   securityGroupIds:
  #     - sg-0823d8298e45c9bef
  #   subnetIds:
  #     - subnet-0d13e14b766a4a8bf
  #     - subnet-0e9cf3f7616ca9817
  timeout: 30

package:
  individually: true

functions:
  main:
    handler: src/main/handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

  otherfunc
    ...

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  # - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-split-stacks

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'
    # packagerOptions:
    #   scripts:
    #     - prisma generate
  prune:
    automatic: true
    number: 3
```

before I exclude the `aws-sdk` in `webpack` like this:

```
custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
```

but after the error show, i make the change like this:

```
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
```

after the `webpack` change + `model` both 2 flags disable. The error did not show again.
just report an issue here, maybe need a fix on `aws-sdk` in this lib.

Thanks!
