### ISSUE TITLE
[BUG] ERROR Unhandled Promise Rejection "errorType": "Runtime.UnhandledPromiseRejection" Table already exists

### ISSUE THREAD

**Issue by yeukfei02** [dynamoose/dynamoose#1123]
### Summary:

It shows an error about the table already exists but the model should be able to handle it.
There should be no need to add `create` / `waitForActive` to false

#### Schema
```
// import env from 'dotenv';
// env.config();

import dynamoose from 'dynamoose';
dynamoose.aws.sdk.config.update({
  accessKeyId: process.env.MY_AWS_ACCESS_KEY,
  secretAccessKey: process.env.MY_AWS_SECRET_ACCESS_KEY,
  region: 'ap-southeast-1',
});

const recordTimeSchema = new dynamoose.Schema(
  {
    id: String,
    partner_name: String,
    partner_store_code: {
      type: String,
      rangeKey: true,
    },
  },
  {
    saveUnknown: true,
    timestamps: {
      createdAt: 'createdAt',
      updatedAt: 'updatedAt',
    },
  },
);

```

#### Model
```
let tableName = '';
if (process.env.NODE_ENV === 'development' || process.env.NODE_ENV === 'test') {
  tableName = 'k11-open-api-record-time-uat';
} else {
  tableName = 'k11-open-api-record-time-prod';
}

const recordTimeModel = dynamoose.model(tableName, recordTimeSchema, {
  create: false,
  waitForActive: { enabled: false },
});

export default recordTimeModel;
```

#### General

serverless.yml
```
org: keysocapp
app: k11-open-api
service: k11-open-api

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  apiName: k11-open-api-dev
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: development
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
    K11_OPEN_API_JWT_SECRET_DEV: ${param:K11_OPEN_API_JWT_SECRET_DEV}
    K11_OPEN_API_JWT_SECRET_PROD: ${param:K11_OPEN_API_JWT_SECRET_PROD}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: K11 Open Api Staging
  lambdaHashingVersion: 20201221
  # vpc:
  #   securityGroupIds:
  #     - sg-0823d8298e45c9bef
  #   subnetIds:
  #     - subnet-0d13e14b766a4a8bf
  #     - subnet-0e9cf3f7616ca9817
  timeout: 30

package:
  individually: true

functions:
  main:
    handler: src/main/handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

  otherfunc
    ...

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  # - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-split-stacks

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'
    # packagerOptions:
    #   scripts:
    #     - prisma generate
  prune:
    automatic: true
    number: 3
```

### Current output and behavior (including stack trace):

```
2021-02-05T03:18:44.062Z	1abd6db3-2523-4759-a9b6-4efb26d1bf14	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
    "reason": {
        "errorType": "ResourceInUseException",
        "errorMessage": "Table already exists: k11-open-api-record-time-prod",
        "code": "ResourceInUseException",
        "message": "Table already exists: k11-open-api-record-time-prod",
        "time": "2021-02-05T03:18:44.059Z",
        "requestId": "HD5AFEAVI78KITG8LEI8KKVRVVVV4KQNSO5AEMVJF66Q9ASUAAJG",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 110.1554075775096,
        "stack": [
            "ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
            "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)",
            "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:495:21)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

error show **ResourceInUseException: Table already exists**

### Expected output and behavior:

there should be no error on above, because the model will check if table doesn't exist then create table.
and I don't need to set `create` + `waitForActive` to false.

### Environment:

Operating System: macos
Operating System Version: 10.15.7 
Node.js version (`node -v`): 12.20.0
NPM version: (`npm -v`): 6.14.8
Dynamoose version: 2.7.0

### Other information (if applicable):

```
const recordTimeModel = dynamoose.model(tableName, recordTimeSchema, {
  create: false,
  waitForActive: { enabled: false },
});
```

temp fix is I make `create` to false and `waitForActive` to false in prod env. then I don't see the error above.

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

Thanks!
