### ISSUE TITLE
[BUG] Getting validation exception on Schema with Hash and Range Key

### ISSUE THREAD

**Issue by jaekunchoi** [dynamoose/dynamoose#1683]
### Summary:

Is there a reason why this isn't working? I tried many variations in schema with no luck. Any help would be great

#### Schema
```
export const ContentSchema = new dynamoose.Schema({
  task_id: {
    type: String,
    hashKey: true,
    index: {
      type: 'local',
      rangeKey: 'created_at',
    },
  },
});
```
Interface
```
export interface ContentKey {
  task_id: string;
  created_at: string;
}

export interface Content extends ContentKey {
  user_id: string;
  keywords: object;
  results: object;
  search_language: string;
  search_location: string;
  seed_keyword: string;
  task_status: string;
  updated_at: string;
}
```

Service in Nest JS
```
@Injectable()
export class ContentService {
  private readonly logger = new Logger(ContentService.name);
  constructor(
    @InjectModel('TaskStatus')
    private contentModel: Model<Content, ContentKey>,
  ) {}

  // taskKey object is { task_id: '12345', created_at: 'date_string' }
  async updateTask(taskKey: ContentKey, task: TaskDto) {
    const rangeKey = ContentSchema.rangeKey;
    return this.contentModel.update(taskKey, task);
  }
}
```
I am also creating table separately with Serverless

```
TaskStatus:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskStatus
        StreamSpecification: 
          StreamViewType: NEW_AND_OLD_IMAGES  
        AttributeDefinitions:
          - AttributeName: task_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: task_id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
        - IndexName: TaskStatus
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
```

### Current output and behavior (including stack trace):

```
ValidationException: The provided key element does not match the schema
    at throwDefaultError (/Users/test/business/code/backend/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /Users/test/business/code/backend/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/Users/test/business/code/backend/node_modules/@aws-sdk/client-dynamodb/dist-cjs/index.js:2231:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/test/business/code/backend/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at /Users/test/business/code/backend/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at /Users/test/business/code/backend/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at /Users/test/business/code/backend/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at main (/Users/test/business/code/backend/node_modules/dynamoose/dist/aws/ddb/internal.js:6:20)
    at /Users/test/business/code/backend/node_modules/dynamoose/dist/Model/index.js:667:34
```

### Expected output and behavior:

No error on update and item is updated in DynamoDB

### Environment:

Operating System: Mac
Operating System Version: Sonoma 14.3.1
Node.js version (`node -v`): v18.16.1
NPM version: (`npm -v`): 9.7.2
Dynamoose version: 4.0.0

### Other information (if applicable):

I'm using [nestjs-dynamoose](https://github.com/hardyscc/nestjs-dynamoose) but this error is `Dynamoose` specific as that package is just a wrapper

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose
