### ISSUE TITLE
Website Deployment

### ISSUE THREAD

**Issue by fishcharlie** [dynamoose/dynamoose#828]
We need to get the documentation website deployment process working. The current plan is to deploy using GitHub Actions when the version is not a prerelease version.

```
jobs:
  publishsite:
    needs: getinfo
    runs-on: ubuntu-latest
    if: needs.getinfo.outputs.npmtag == 'latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      # TODO: need to get into correct directory (docs)
      - run: npm ci
      - run: npm run build
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'docs/build'
```

---

This issue is currently on hold until we fix up the DNS settings for the domain.
