### ISSUE TITLE
[BUG] Cant do a query using secondary index

### ISSUE THREAD

**Issue by netochaves** [dynamoose/dynamoose#966]
### Summary:
I'm try to do a query using a secondary index but it me returns an error

### Code sample
```js
const result = await this.Model.query({ [type]: { eq: value } })
      .using(index)
      .limit(1)
      .exec();
```
#### Schema
```js
const Schema = new Dynamoose.Schema({
  id: {
    type: String,
    hashKey: true,
    default: () => uuid(),
  },
  cpf: String,
  cnpj: String,
  status: String,
});
```
#### Model
```
DbIdWallReport:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: DbIdWallReport
    BillingMode: PAY_PER_REQUEST
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: !If [Prod, true, false]
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: idWallNumber
        AttributeType: S
      - AttributeName: cpf
        AttributeType: S
      - AttributeName: cnpj
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: IdWallNumberIndex
        KeySchema:
          - AttributeName: idWallNumber
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: IdWallCpfIndex
        KeySchema:
          - AttributeName: cpf
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: IdWallCnpjIndex
        KeySchema:
          - AttributeName: cnpj
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    Tags:
      - { Key: Project, Value: !Ref Project }
      - { Key: Environment, Value: !Ref Environment }
```

### Current output and behavior (including stack trace):

Returns an error:

```
WARNING:  ValidationException: Either the KeyConditions or KeyConditionExpression parameter must be specified in the request.
```

### Expected output and behavior:
Complete the query and return the result.

### Environment:

Operating System: PopOS
Operating System Version: 20.04 LTS
Node.js version (`node -v`):12.13.0
NPM version: (`npm -v`):6.12.0
Dynamoose version:2.2.1

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose
